name: Build

on: push

jobs:
  build-pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/latex:latest
        with:
          args: "-d config.yaml" 
      - uses: actions/upload-artifact@master
        with:
          name: index.html
          path: index.html

